# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_part', models.CharField(max_length=70, unique=True)),
                ('description', models.CharField(db_index=True, max_length=100)),
                ('inventory_type', models.CharField(db_index=True, max_length=100)),
                ('image', models.ImageField(null=True, upload_to='toolcrib/static/media')),
                ('category', models.CharField(choices=[('1', 'SUPPLY'), ('2', 'EXPERT PARTS')], default='1', max_length=1)),
                ('clas', models.CharField(choices=[('1', 'MXN'), ('2', 'USD')], default='1', max_length=1)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('max_quantity', models.PositiveIntegerField()),
                ('min_quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
