# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toolcrib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Pennding'), ('2', 'Approved'), ('3', 'Canceled'), ('4', 'Done')], default='1', max_length=1)),
                ('level', models.CharField(choices=[('1', 'Not Urgent'), ('2', 'Regular'), ('3', 'Urgent')], default='1', max_length=1)),
                ('cost_center', models.CharField(max_length=100)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('date_done', models.DateTimeField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='superviced_order_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_set', to='toolcrib.Order')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_detail_set', to='toolcrib.Part')),
            ],
        ),
    ]
