# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolcrib', '0002_order_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
