# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolcrib', '0003_auto_20180501_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='image',
            field=models.ImageField(null=True, upload_to='parts_img/'),
        ),
    ]
