# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import toolcrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('toolcrib', '0004_auto_20180508_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='level',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.CharField(choices=[('1', 'SUPPLY'), ('2', 'SPARE PARTS')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='part',
            name='image',
            field=models.ImageField(null=True, upload_to=toolcrib.models.unique_file_path),
        ),
    ]
